apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: md4c8w2qg-java-springboot
  janus-idp.io/tekton: md4c8w2qg-java-springboot
  backstage.io/kubernetes-id: md4c8w2qg-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: md4c8w2qg-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
